name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        sudo apt update
        sudo apt install libgtest-dev libgflags-dev openssl libssl-dev protobuf-compiler
    - name: make
      run: |
        cd src
        make -f certifier.mak
        rm ./*.o
        make -f certifier_tests.mak
        ./certifier_tests.exe
        cd ../utilities
        make -f cert_utility.mak
        make -f policy_utilities.mak
