name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #! -------------------------------------------------------------------------
    - name: dependencies
      run: |
        sudo apt update -y
        sudo apt install -y clang-format-11 libgtest-dev libgflags-dev openssl libssl-dev protobuf-compiler protoc-gen-go golang-go cmake
        sudo apt install -y python3 pylint
        pip install pytest

        # Needed for Python bindings support
        sudo apt install -y swig

        set -x
        which protoc

        protoc --version

        echo " "
        ls -aFlrt /usr/include/google/protobuf/port_def.inc

        echo " "
        ls -aFlrt /usr/include/google/protobuf

        echo " "
        ls -aFlrt /usr/local/include

        echo " "
        which swig
        swig --version

        echo " "
        which g++
        g++ --version

        echo " "
        which clang-format
        clang-format --version

        echo " "
        which clang-format-11
        clang-format-11 --version

        echo " "
        set +x
